### ISSUE TITLE
correct fork, code sharing with SlavaRa code, etc...

### ISSUE THREAD

**Issue by profelis** [deprecated-armory3d/dragonbones_kha#1]
Why have you forked repository manual, without github integration? Which allow create simple pull requests, work collaborative, etc.

**Comment by luboslenco** [comment]
Hello,

Will fix this, had no idea someone would discover this already. However, sharing the code will not be an easy task. Original DragonBones are strongly dependant on Flash API while Kha has nothing to do with it. Currently Flash classes are 'emulated' thanks to OpenFL project, but ideally this gets removed and everything is connected straight to Kha API. That means that examples and project files are incompatible also.

With this said, I am thankful that SlavaRa has gone through the effort of porting and made code available for the rest of us. That's why I also provided this one, for the users of Kha library - to give back.

Thanks,
Lubos
